#!/usr/bin/env python3
"""Run a file-mediated, independent-context adversarial modeling review.

The script uses a DashScope OpenAI-compatible endpoint. It deliberately keeps
LLM reasoning separate from numerical computation: agents may recommend or
review routes, but the final judge must cite files generated by real scripts.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from typing import Any

DEFAULT_ENDPOINT = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
DEFAULT_MODEL = "qwen-plus"

SOLVER_SYSTEM = """You are the solver agent for a mathematical-modeling contest. Work only from the supplied brief and artifacts. Propose multiple materially different routes, state assumptions, and distinguish a mathematical model from a numerical algorithm. Do not invent numerical results. Any claimed result must name its real output file. End with a concise route register containing: route_id, objective, hard constraints, executable evidence required, and rejection risks."""
CRITIC_SYSTEMS = {
    "method": """You are an adversarial mathematical-modeling method reviewer. Find structural errors in objective functions, assumptions, linearization, temporal constraints, and claims of optimality. Do not solve the problem. Return a numbered defect list with severity (BLOCKER/MAJOR/MINOR), evidence, and a test the solver must run. If no blocker remains, say so explicitly.""",
    "data": """You are an adversarial data and reproducibility reviewer. Audit data provenance, joins, units, parameter assumptions, missing templates, code-to-result traceability, and whether reported values came from real computation. Do not propose a new full solution. Return a numbered defect list with severity, evidence, and required verification.""",
    "operations": """You are an adversarial operations and domain reviewer. Infer the domain only from the brief. Audit whether decisions are implementable, whether units and operational constraints are complete, and whether the reported solution can be independently checked. Do not introduce agricultural rules unless the problem is agricultural. Return a numbered defect list with severity, evidence, and required verification.""",
}
REVISER_SYSTEM = """You are the revision agent. Read the solver proposal and independent reviews. For every numbered finding, decide ACCEPT, PARTIAL_ACCEPT, or REJECT, justify the decision, and specify the exact model/code/evidence change. Never claim execution that is not present in an artifact. Produce a revised route register and an explicit list of scripts that must be run before final judgment."""
JUDGE_SYSTEM = """You are an independent final judge. Decide from the brief, reviews, revision, verified evidence excerpts, and machine gate. Do not reward eloquence. A file name alone is not evidence, and a summary in the brief cannot prove a numerical claim. You may return PASS only when the machine gate explicitly passes; otherwise return REVISE or REJECT. Judge each route on its declared terms and do not demand global optimality from a clearly labeled feasible heuristic. Return valid JSON only with keys verdict (PASS/REVISE/REJECT), selected_routes (array), blockers (array), required_evidence (array), and rationale (string)."""


def call_model(system: str, user: str, endpoint: str, model: str, timeout: int) -> str:
    key = os.environ.get("DASHSCOPE_API_KEY")
    if not key:
        raise RuntimeError("DASHSCOPE_API_KEY is not configured")
    payload = json.dumps({
        "model": model,
        "temperature": 0.2,
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
    }).encode("utf-8")
    request = urllib.request.Request(endpoint, data=payload, method="POST", headers={
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
    })
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")[:1000]
        raise RuntimeError(f"model API HTTP {exc.code}: {detail}") from exc
    try:
        return body["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError, TypeError) as exc:
        raise RuntimeError(f"unexpected model response: {body}") from exc


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def artifact_manifest(root: Path) -> str:
    files = [p for p in root.rglob("*") if p.is_file() and p.stat().st_size <= 2_000_000]
    return "\n".join(f"- {p.relative_to(root)} ({p.stat().st_size} bytes)" for p in sorted(files)) or "- no artifacts found"


def evidence_digest(root: Path, max_total_chars: int = 30000) -> str:
    allowed = {".json", ".md", ".csv", ".txt", ".log"}
    selected = []
    remaining = max_total_chars
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in allowed or path.stat().st_size > 1_000_000:
            continue
        name = path.name.lower()
        if not any(term in name for term in ("contract", "judge", "gate", "summary", "audit", "registry", "comparison")):
            continue
        content = read_text(path)[: min(8000, remaining)]
        selected.append(f"## {path.relative_to(root)}\n{content}")
        remaining -= len(content)
        if remaining <= 0:
            break
    return "\n\n".join(selected) or "- no structured evidence excerpts found"


def run_verification_script(script: Path, artifact_root: Path, run_dir: Path, round_no: int, timeout: int) -> dict[str, Any]:
    script = script.resolve()
    root = artifact_root.resolve()
    if root not in script.parents:
        raise ValueError("verification script must be inside artifact-root")
    proc = subprocess.run([sys.executable, str(script)], cwd=root, text=True, encoding="utf-8", errors="replace", capture_output=True, timeout=timeout)
    write_text(run_dir / f"{round_no + 1:02d}_verification.stdout.txt", proc.stdout)
    write_text(run_dir / f"{round_no + 1:02d}_verification.stderr.txt", proc.stderr)
    result = {"script": str(script), "exit_code": proc.returncode, "passed": proc.returncode == 0}
    write_text(run_dir / f"{round_no + 1:02d}_verification.json", json.dumps(result, ensure_ascii=False, indent=2))
    return result


def parse_judgment(text: str) -> dict[str, Any]:
    """Recover a JSON object when a model adds a short preamble or code fence."""
    candidate = text.strip()
    if candidate.startswith("```"):
        candidate = candidate.split("\n", 1)[-1]
        candidate = candidate.rsplit("```", 1)[0].strip()
    try:
        return validate_judgment(json.loads(candidate))
    except json.JSONDecodeError:
        start, end = candidate.find("{"), candidate.rfind("}")
        if start >= 0 and end > start:
            return validate_judgment(json.loads(candidate[start : end + 1]))
        raise


def validate_judgment(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict):
        raise ValueError("judge response must be an object")
    required = {"verdict", "selected_routes", "blockers", "required_evidence", "rationale"}
    if required - payload.keys():
        raise ValueError(f"judge response missing fields: {sorted(required - payload.keys())}")
    if payload["verdict"] not in {"PASS", "REVISE", "REJECT"}:
        raise ValueError("judge verdict is invalid")
    if not all(isinstance(payload[name], list) for name in ("selected_routes", "blockers", "required_evidence")) or not isinstance(payload["rationale"], str):
        raise ValueError("judge response field types are invalid")
    return payload


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_machine_gate(gate: Any, gate_path: Path) -> tuple[bool, list[str]]:
    issues = []
    if not isinstance(gate, dict) or str(gate.get("verdict", "")).lower() != "pass":
        issues.append("gate_verdict_not_pass")
        return False, issues
    if not gate.get("problem_id") or not gate.get("run_id") or not gate.get("contract_hash"):
        issues.append("incomplete_gate_binding")
    for binding_name in ("input_bindings", "code_bindings"):
        bindings = gate.get(binding_name)
        if not isinstance(bindings, list) or not bindings:
            issues.append(f"missing_gate_{binding_name}")
            continue
        for binding in bindings:
            path = Path(binding.get("path", "")) if isinstance(binding, dict) else Path()
            expected = binding.get("sha256") if isinstance(binding, dict) else None
            if not path.is_file() or not expected or sha256(path) != expected:
                issues.append(f"gate_binding_mismatch:{binding_name}:{path}")
    layers = gate.get("gate_layers")
    if not isinstance(layers, dict) or not layers or any(not isinstance(value, dict) or value.get("pass") is not True for value in layers.values()):
        issues.append("gate_layer_not_passed")
    return not issues, issues


def args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Independent-context multi-agent modeling workflow")
    parser.add_argument("--brief", type=Path, required=True, help="Problem brief in UTF-8 text or Markdown")
    parser.add_argument("--artifact-root", type=Path, required=True, help="Folder containing data/code/results available to agents")
    parser.add_argument("--run-dir", type=Path, required=True, help="Folder for this workflow's transcript")
    parser.add_argument("--endpoint", default=os.environ.get("DASHSCOPE_BASE_URL", DEFAULT_ENDPOINT))
    parser.add_argument("--model", default=os.environ.get("DASHSCOPE_MODEL", DEFAULT_MODEL))
    parser.add_argument("--timeout", type=int, default=90)
    parser.add_argument("--rounds", type=int, default=1, choices=range(1, 4))
    parser.add_argument("--verification-script", type=Path, default=None, help="Optional existing verifier inside artifact-root.")
    parser.add_argument("--machine-gate", type=Path, default=None, help="Optional JSON gate inside artifact-root; PASS requires verdict=pass.")
    return parser.parse_args()


def main() -> None:
    config = args()
    if not config.brief.is_file():
        raise FileNotFoundError(config.brief)
    if not config.artifact_root.is_dir():
        raise NotADirectoryError(config.artifact_root)
    config.run_dir.mkdir(parents=True, exist_ok=True)
    brief = read_text(config.brief)
    manifest = artifact_manifest(config.artifact_root)
    metadata = {
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "brief": str(config.brief),
        "artifact_root": str(config.artifact_root),
        "endpoint": config.endpoint,
        "model": config.model,
        "rounds": config.rounds,
        "roles": ["solver", *[f"critic_{name}" for name in CRITIC_SYSTEMS], "reviser", "judge"],
    }
    write_text(config.run_dir / "run_metadata.json", json.dumps(metadata, ensure_ascii=False, indent=2))

    solver_prompt = f"""## Problem brief\n{brief}\n\n## Available artifact manifest\n{manifest}\n\nCreate the initial proposal. Mention only files you can see in the manifest; request real computation where evidence is absent."""
    proposal = call_model(SOLVER_SYSTEM, solver_prompt, config.endpoint, config.model, config.timeout)
    write_text(config.run_dir / "01_solver_proposal.md", proposal)

    current_proposal = proposal
    final_response: dict[str, Any] = {}
    for round_no in range(1, config.rounds + 1):
        review_prompt = f"""## Problem brief\n{brief}\n\n## Solver proposal\n{current_proposal}\n\n## Available artifact manifest\n{artifact_manifest(config.artifact_root)}\n\nReview independently. Do not assume omitted evidence exists."""
        reviews: dict[str, str] = {}
        with ThreadPoolExecutor(max_workers=len(CRITIC_SYSTEMS)) as pool:
            futures = {pool.submit(call_model, system, review_prompt, config.endpoint, config.model, config.timeout): name for name, system in CRITIC_SYSTEMS.items()}
            for future in as_completed(futures):
                name = futures[future]
                reviews[name] = future.result()
        for name, text in reviews.items():
            write_text(config.run_dir / f"{round_no + 1:02d}_critic_{name}.md", text)

        combined_reviews = "\n\n".join(f"## {name} review\n{text}" for name, text in reviews.items())
        revise_prompt = f"""## Problem brief\n{brief}\n\n## Solver proposal\n{current_proposal}\n\n## Independent reviews\n{combined_reviews}\n\n## Current artifact manifest\n{artifact_manifest(config.artifact_root)}\n\nWrite the revision response."""
        revision = call_model(REVISER_SYSTEM, revise_prompt, config.endpoint, config.model, config.timeout)
        write_text(config.run_dir / f"{round_no + 1:02d}_reviser_response.md", revision)

        verification = None
        if config.verification_script:
            verification = run_verification_script(config.verification_script, config.artifact_root, config.run_dir, round_no, config.timeout)
        gate = {"verdict": "missing"}
        gate_issues = ["machine_gate_missing"]
        if config.machine_gate:
            gate_path = config.machine_gate.resolve()
            if config.artifact_root.resolve() not in gate_path.parents or not gate_path.is_file():
                raise ValueError("machine gate must be an existing JSON file inside artifact-root")
            gate = json.loads(read_text(gate_path))
            gate_valid, gate_issues = validate_machine_gate(gate, gate_path)
        else:
            gate_valid = False
        gate_pass = gate_valid and verification is not None and verification["passed"]
        if verification is None:
            gate_issues.append("independent_verification_missing")
        elif not verification["passed"]:
            gate_issues.append("independent_verification_failed")

        judge_prompt = f"""## Problem brief\n{brief}\n\n## Proposal\n{current_proposal}\n\n## Reviews\n{combined_reviews}\n\n## Revision response\n{revision}\n\n## Actual artifact manifest\n{artifact_manifest(config.artifact_root)}\n\n## Verified evidence excerpts\n{evidence_digest(config.artifact_root)}\n\n## Verification result\n{json.dumps(verification, ensure_ascii=False)}\n\n## Machine gate\n{json.dumps(gate, ensure_ascii=False)}\n\n## Gate issues\n{json.dumps(gate_issues, ensure_ascii=False)}\n\nMachine gate pass={gate_pass}. Return the judgment JSON."""
        judge_raw = call_model(JUDGE_SYSTEM, judge_prompt, config.endpoint, config.model, config.timeout)
        write_text(config.run_dir / f"{round_no + 1:02d}_judge_raw.json", judge_raw)
        try:
            final_response = parse_judgment(judge_raw)
        except (json.JSONDecodeError, ValueError, TypeError):
            final_response = {"verdict": "REVISE", "selected_routes": [], "blockers": ["judge response was not valid JSON"], "required_evidence": [], "rationale": judge_raw}
        if not gate_pass and final_response.get("verdict") == "PASS":
            final_response["verdict"] = "REVISE"
            final_response.setdefault("blockers", []).append("machine gate or verification did not pass")
        write_text(config.run_dir / f"{round_no + 1:02d}_judge.json", json.dumps(final_response, ensure_ascii=False, indent=2))
        if final_response.get("verdict") in {"PASS", "REJECT"}:
            break
        current_proposal = revision

    metadata["finished_at"] = datetime.now().isoformat(timespec="seconds")
    metadata["final_verdict"] = final_response.get("verdict", "REVISE")
    write_text(config.run_dir / "run_metadata.json", json.dumps(metadata, ensure_ascii=False, indent=2))
    print(json.dumps({"run_dir": str(config.run_dir), "verdict": metadata["final_verdict"]}, ensure_ascii=False))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"multi-agent workflow failed: {exc}", file=sys.stderr)
        raise
